version: "3.7"

services:
  postgres:
    image: postgres:16.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=opentelemetry_ecto_test
    ports:
      - 5432:5432

  mariadb:
    image: mariadb:11.0
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
      - MARIADB_USER=mariadb
      - MARIADB_PASSWORD=mariadb
      - MARIADB_DATABASE=opentelemetry_ecto_test
    ports:
      - 3306:3306
